### ISSUE TITLE
can't /item "revival root" <t> while in mog garden

### ISSUE THREAD

**Issue by benjaminGitHub** [Selindrile/GearSwap#12] opened 2018-11-18 00:40 UTC
with these files included in gearswap and with gearswap loaded, I can't use the /item command while in my Mog Garden

**Comment by Selindrile** [comment] 2018-11-18 07:32
I actually meant to fix that a while back, thank you for the reminder, will do so now.

**Comment by Selindrile** [comment] 2018-11-18 08:05
After looking into it, it looks like I already did fix this at some point... I have no issue using items in mog garden, I won't close this yet but, can't seem to make it happen, can you explain the exact circumstances and error message?

**Comment by benjaminGitHub** [comment] 2018-11-18 08:39
The exact error message is "Abort" You are currently in a Mog House zone." I can trade the revival root to the Garden Furrow #2 through the menu but not by using /item "revival root" <t>. If i //lua u gearswap, then i can trade items through /item again.

**Comment by Selindrile** [comment] 2018-11-18 09:12
That's odd, that specific message is in filtered_action, which means it should only pop up if FFXI was already going to give you an error message, and I couldn't get that to pop up using /item myself.

**Comment by thatdumbguy** [comment] 2018-11-19 02:36
I can reproduce this issue. Target any Furrow with a revival root in your inventory, and /item "revival root" <t>, works fine without gearswap loaded, gives the abort message stated above when it is loaded.

**Comment by Selindrile** [comment] 2018-11-19 03:17
I tested just now and yeah, I get the issue as well, it just seems really odd that gearswap is calling filtered_action in this situation, but that's the only way this is possible, I guess I'll just write an exception.

**Comment by Selindrile** [comment] 2018-11-19 03:33
Exception added, though still have no idea why filtered_action is called when you trade an item in the mog house, I'd post an issue on Byrth's tracker but considering how long it's been since anything's been answered there I'm just going to call this closed for now.

**Closed by Selindrile** 2018-11-19 03:33 UTC

**Comment by DoubleMCA** [comment] 2025-12-29 04:37
How was this fixed? I'm running into the same issue with Arborscent Seeds and i am not getting anywhere with a fix.

**Comment by Selindrile** [comment] 2025-12-29 05:59
Thais was me breaking my own exception when I moved something elsewhere, I'll fix!
